version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mySQL_Container
    environment:
      MYSQL_DATABASE: bank
      MYSQL_ROOT: root
      MYSQL_ROOT_PASSWORD: Ivomama1230
      MYSQL_PASSWORD: Ivomama1230
    ports:
      - "3306:3306"
    networks:
      - springapimysql-net
    volumes:
      - ./data:/var/lib/mysql
  api_service:
    build: .
    restart: on-failure
    ports:
      - "8080:8080"
    networks:
      - springapimysql-net
    environment:
      - spring.datasource.url=jdbc:mysql://mysql:3306/bank?allowPublicKeyRetrieval=true
    depends_on:
      - mysql

    volumes:
      - .m2:/root/.m2

networks:
  springapimysql-net:
    driver: bridge