version: '3.8'
services:
  mysql:
    image: mysql:latest
    container_name: mySQL_Container
    environment:
      MYSQL_DATABASE: bank
      MYSQL_USER: root
      MYSQL_PASSWORD: Ivomama1230
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql